[project]
name = "midnight-zmk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "anytree>=2.13.0",
    "canopen>=2.4.1",
    "cbor>=1.0.0",
    "click>=8.5.0",
    "cryptography>=50.0.1",
    "ecdsa>=0.19.2",
    "intelhex>=2.3.0",
    "packaging>=26.3",
    "pillow>=12.3.0",
    "progress>=1.6.1",
    "protobuf>=7.36.2",
    "psutil>=7.2.2",
    "pyelftools>=0.33",
    "pykwalify>=1.8.0",
    "pylink-square>=1.7.0",
    "pyocd>=0.45.1",
    "pyserial>=3.5",
    "python-magic>=0.4.27",
    "pyyaml>=6.0.3",
    "requests>=2.34.2",
    "setuptools<70",
    "west>=1.5.0",
]
